name: Pandora plugin ARNN CI

on:
  push:
  schedule:
    - cron: 0 2 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip freeze
      - name: Install Pandora plugin ARNN
        run: |
          pip install .[dev]
          pip freeze
      - name: Test with pytest
        run: |
          pytest --junitxml=pytest-report.xml --cov-config=.coveragerc --cov-report xml --cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CNES/Pandora_plugin_arnn
      - name: Create source distrubition
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          pip install build
          python -m build
      - name: Publish package on pypi
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
